/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedActivityLogsIndexRouteImport } from './routes/_authenticated/activity-logs/index'
import { Route as AuthenticatedAnnouncementsIndexRouteImport } from './routes/_authenticated/announcements/index'
import { Route as AuthenticatedBillsIndexRouteImport } from './routes/_authenticated/bills/index'
import { Route as AuthenticatedContactMessagesIndexRouteImport } from './routes/_authenticated/contact-messages/index'
import { Route as AuthenticatedDueTypesIndexRouteImport } from './routes/_authenticated/due-types/index'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedExpenseCategoriesIndexRouteImport } from './routes/_authenticated/expense-categories/index'
import { Route as AuthenticatedExpensesIndexRouteImport } from './routes/_authenticated/expenses/index'
import { Route as AuthenticatedForumIndexRouteImport } from './routes/_authenticated/forum/index'
import { Route as AuthenticatedForumThreadIdRouteImport } from './routes/_authenticated/forum/$threadId'
import { Route as AuthenticatedHousesIndexRouteImport } from './routes/_authenticated/houses/index'
import { Route as AuthenticatedHousesIdRouteImport } from './routes/_authenticated/houses/$id'
import { Route as AuthenticatedNotificationsIndexRouteImport } from './routes/_authenticated/notifications/index'
import { Route as AuthenticatedPagesIndexRouteImport } from './routes/_authenticated/pages/index'
import { Route as AuthenticatedPaymentsIndexRouteImport } from './routes/_authenticated/payments/index'
import { Route as AuthenticatedPengumumanIndexRouteImport } from './routes/_authenticated/pengumuman/index'
import { Route as AuthenticatedPermissionsIndexRouteImport } from './routes/_authenticated/permissions/index'
import { Route as AuthenticatedPollsIndexRouteImport } from './routes/_authenticated/polls/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedResidentsIndexRouteImport } from './routes/_authenticated/residents/index'
import { Route as AuthenticatedResidentsIdRouteImport } from './routes/_authenticated/residents/$id'
import { Route as AuthenticatedRolesIndexRouteImport } from './routes/_authenticated/roles/index'
import { Route as AuthenticatedTicketsIndexRouteImport } from './routes/_authenticated/tickets/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivityLogsIndexRoute =
  AuthenticatedActivityLogsIndexRouteImport.update({
    id: '/activity-logs/',
    path: '/activity-logs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnnouncementsIndexRoute =
  AuthenticatedAnnouncementsIndexRouteImport.update({
    id: '/announcements/',
    path: '/announcements/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBillsIndexRoute = AuthenticatedBillsIndexRouteImport.update({
  id: '/bills/',
  path: '/bills/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactMessagesIndexRoute =
  AuthenticatedContactMessagesIndexRouteImport.update({
    id: '/contact-messages/',
    path: '/contact-messages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDueTypesIndexRoute =
  AuthenticatedDueTypesIndexRouteImport.update({
    id: '/due-types/',
    path: '/due-types/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExpenseCategoriesIndexRoute =
  AuthenticatedExpenseCategoriesIndexRouteImport.update({
    id: '/expense-categories/',
    path: '/expense-categories/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExpensesIndexRoute =
  AuthenticatedExpensesIndexRouteImport.update({
    id: '/expenses/',
    path: '/expenses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedForumIndexRoute = AuthenticatedForumIndexRouteImport.update({
  id: '/forum/',
  path: '/forum/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedForumThreadIdRoute =
  AuthenticatedForumThreadIdRouteImport.update({
    id: '/forum/$threadId',
    path: '/forum/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHousesIndexRoute =
  AuthenticatedHousesIndexRouteImport.update({
    id: '/houses/',
    path: '/houses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHousesIdRoute = AuthenticatedHousesIdRouteImport.update({
  id: '/houses/$id',
  path: '/houses/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsIndexRoute =
  AuthenticatedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPagesIndexRoute = AuthenticatedPagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsIndexRoute =
  AuthenticatedPaymentsIndexRouteImport.update({
    id: '/payments/',
    path: '/payments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPengumumanIndexRoute =
  AuthenticatedPengumumanIndexRouteImport.update({
    id: '/pengumuman/',
    path: '/pengumuman/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPermissionsIndexRoute =
  AuthenticatedPermissionsIndexRouteImport.update({
    id: '/permissions/',
    path: '/permissions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPollsIndexRoute = AuthenticatedPollsIndexRouteImport.update({
  id: '/polls/',
  path: '/polls/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResidentsIndexRoute =
  AuthenticatedResidentsIndexRouteImport.update({
    id: '/residents/',
    path: '/residents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResidentsIdRoute =
  AuthenticatedResidentsIdRouteImport.update({
    id: '/residents/$id',
    path: '/residents/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRolesIndexRoute = AuthenticatedRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTicketsIndexRoute =
  AuthenticatedTicketsIndexRouteImport.update({
    id: '/tickets/',
    path: '/tickets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/forum/$threadId': typeof AuthenticatedForumThreadIdRoute
  '/houses/$id': typeof AuthenticatedHousesIdRoute
  '/residents/$id': typeof AuthenticatedResidentsIdRoute
  '/activity-logs/': typeof AuthenticatedActivityLogsIndexRoute
  '/announcements/': typeof AuthenticatedAnnouncementsIndexRoute
  '/bills/': typeof AuthenticatedBillsIndexRoute
  '/contact-messages/': typeof AuthenticatedContactMessagesIndexRoute
  '/due-types/': typeof AuthenticatedDueTypesIndexRoute
  '/expense-categories/': typeof AuthenticatedExpenseCategoriesIndexRoute
  '/expenses/': typeof AuthenticatedExpensesIndexRoute
  '/forum/': typeof AuthenticatedForumIndexRoute
  '/houses/': typeof AuthenticatedHousesIndexRoute
  '/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/pages/': typeof AuthenticatedPagesIndexRoute
  '/payments/': typeof AuthenticatedPaymentsIndexRoute
  '/pengumuman/': typeof AuthenticatedPengumumanIndexRoute
  '/permissions/': typeof AuthenticatedPermissionsIndexRoute
  '/polls/': typeof AuthenticatedPollsIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/residents/': typeof AuthenticatedResidentsIndexRoute
  '/roles/': typeof AuthenticatedRolesIndexRoute
  '/tickets/': typeof AuthenticatedTicketsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/forum/$threadId': typeof AuthenticatedForumThreadIdRoute
  '/houses/$id': typeof AuthenticatedHousesIdRoute
  '/residents/$id': typeof AuthenticatedResidentsIdRoute
  '/activity-logs': typeof AuthenticatedActivityLogsIndexRoute
  '/announcements': typeof AuthenticatedAnnouncementsIndexRoute
  '/bills': typeof AuthenticatedBillsIndexRoute
  '/contact-messages': typeof AuthenticatedContactMessagesIndexRoute
  '/due-types': typeof AuthenticatedDueTypesIndexRoute
  '/expense-categories': typeof AuthenticatedExpenseCategoriesIndexRoute
  '/expenses': typeof AuthenticatedExpensesIndexRoute
  '/forum': typeof AuthenticatedForumIndexRoute
  '/houses': typeof AuthenticatedHousesIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/pages': typeof AuthenticatedPagesIndexRoute
  '/payments': typeof AuthenticatedPaymentsIndexRoute
  '/pengumuman': typeof AuthenticatedPengumumanIndexRoute
  '/permissions': typeof AuthenticatedPermissionsIndexRoute
  '/polls': typeof AuthenticatedPollsIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/residents': typeof AuthenticatedResidentsIndexRoute
  '/roles': typeof AuthenticatedRolesIndexRoute
  '/tickets': typeof AuthenticatedTicketsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/forum/$threadId': typeof AuthenticatedForumThreadIdRoute
  '/_authenticated/houses/$id': typeof AuthenticatedHousesIdRoute
  '/_authenticated/residents/$id': typeof AuthenticatedResidentsIdRoute
  '/_authenticated/activity-logs/': typeof AuthenticatedActivityLogsIndexRoute
  '/_authenticated/announcements/': typeof AuthenticatedAnnouncementsIndexRoute
  '/_authenticated/bills/': typeof AuthenticatedBillsIndexRoute
  '/_authenticated/contact-messages/': typeof AuthenticatedContactMessagesIndexRoute
  '/_authenticated/due-types/': typeof AuthenticatedDueTypesIndexRoute
  '/_authenticated/expense-categories/': typeof AuthenticatedExpenseCategoriesIndexRoute
  '/_authenticated/expenses/': typeof AuthenticatedExpensesIndexRoute
  '/_authenticated/forum/': typeof AuthenticatedForumIndexRoute
  '/_authenticated/houses/': typeof AuthenticatedHousesIndexRoute
  '/_authenticated/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/_authenticated/pages/': typeof AuthenticatedPagesIndexRoute
  '/_authenticated/payments/': typeof AuthenticatedPaymentsIndexRoute
  '/_authenticated/pengumuman/': typeof AuthenticatedPengumumanIndexRoute
  '/_authenticated/permissions/': typeof AuthenticatedPermissionsIndexRoute
  '/_authenticated/polls/': typeof AuthenticatedPollsIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/residents/': typeof AuthenticatedResidentsIndexRoute
  '/_authenticated/roles/': typeof AuthenticatedRolesIndexRoute
  '/_authenticated/tickets/': typeof AuthenticatedTicketsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/errors/$error'
    | '/forum/$threadId'
    | '/houses/$id'
    | '/residents/$id'
    | '/activity-logs/'
    | '/announcements/'
    | '/bills/'
    | '/contact-messages/'
    | '/due-types/'
    | '/expense-categories/'
    | '/expenses/'
    | '/forum/'
    | '/houses/'
    | '/notifications/'
    | '/pages/'
    | '/payments/'
    | '/pengumuman/'
    | '/permissions/'
    | '/polls/'
    | '/reports/'
    | '/residents/'
    | '/roles/'
    | '/tickets/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/forum/$threadId'
    | '/houses/$id'
    | '/residents/$id'
    | '/activity-logs'
    | '/announcements'
    | '/bills'
    | '/contact-messages'
    | '/due-types'
    | '/expense-categories'
    | '/expenses'
    | '/forum'
    | '/houses'
    | '/notifications'
    | '/pages'
    | '/payments'
    | '/pengumuman'
    | '/permissions'
    | '/polls'
    | '/reports'
    | '/residents'
    | '/roles'
    | '/tickets'
    | '/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/forum/$threadId'
    | '/_authenticated/houses/$id'
    | '/_authenticated/residents/$id'
    | '/_authenticated/activity-logs/'
    | '/_authenticated/announcements/'
    | '/_authenticated/bills/'
    | '/_authenticated/contact-messages/'
    | '/_authenticated/due-types/'
    | '/_authenticated/expense-categories/'
    | '/_authenticated/expenses/'
    | '/_authenticated/forum/'
    | '/_authenticated/houses/'
    | '/_authenticated/notifications/'
    | '/_authenticated/pages/'
    | '/_authenticated/payments/'
    | '/_authenticated/pengumuman/'
    | '/_authenticated/permissions/'
    | '/_authenticated/polls/'
    | '/_authenticated/reports/'
    | '/_authenticated/residents/'
    | '/_authenticated/roles/'
    | '/_authenticated/tickets/'
    | '/_authenticated/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity-logs/': {
      id: '/_authenticated/activity-logs/'
      path: '/activity-logs'
      fullPath: '/activity-logs/'
      preLoaderRoute: typeof AuthenticatedActivityLogsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/announcements/': {
      id: '/_authenticated/announcements/'
      path: '/announcements'
      fullPath: '/announcements/'
      preLoaderRoute: typeof AuthenticatedAnnouncementsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bills/': {
      id: '/_authenticated/bills/'
      path: '/bills'
      fullPath: '/bills/'
      preLoaderRoute: typeof AuthenticatedBillsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contact-messages/': {
      id: '/_authenticated/contact-messages/'
      path: '/contact-messages'
      fullPath: '/contact-messages/'
      preLoaderRoute: typeof AuthenticatedContactMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/due-types/': {
      id: '/_authenticated/due-types/'
      path: '/due-types'
      fullPath: '/due-types/'
      preLoaderRoute: typeof AuthenticatedDueTypesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expense-categories/': {
      id: '/_authenticated/expense-categories/'
      path: '/expense-categories'
      fullPath: '/expense-categories/'
      preLoaderRoute: typeof AuthenticatedExpenseCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses/': {
      id: '/_authenticated/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof AuthenticatedExpensesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forum/': {
      id: '/_authenticated/forum/'
      path: '/forum'
      fullPath: '/forum/'
      preLoaderRoute: typeof AuthenticatedForumIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forum/$threadId': {
      id: '/_authenticated/forum/$threadId'
      path: '/forum/$threadId'
      fullPath: '/forum/$threadId'
      preLoaderRoute: typeof AuthenticatedForumThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/houses/': {
      id: '/_authenticated/houses/'
      path: '/houses'
      fullPath: '/houses/'
      preLoaderRoute: typeof AuthenticatedHousesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/houses/$id': {
      id: '/_authenticated/houses/$id'
      path: '/houses/$id'
      fullPath: '/houses/$id'
      preLoaderRoute: typeof AuthenticatedHousesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications/': {
      id: '/_authenticated/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AuthenticatedNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pages/': {
      id: '/_authenticated/pages/'
      path: '/pages'
      fullPath: '/pages/'
      preLoaderRoute: typeof AuthenticatedPagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments/': {
      id: '/_authenticated/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof AuthenticatedPaymentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pengumuman/': {
      id: '/_authenticated/pengumuman/'
      path: '/pengumuman'
      fullPath: '/pengumuman/'
      preLoaderRoute: typeof AuthenticatedPengumumanIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permissions/': {
      id: '/_authenticated/permissions/'
      path: '/permissions'
      fullPath: '/permissions/'
      preLoaderRoute: typeof AuthenticatedPermissionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/polls/': {
      id: '/_authenticated/polls/'
      path: '/polls'
      fullPath: '/polls/'
      preLoaderRoute: typeof AuthenticatedPollsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/residents/': {
      id: '/_authenticated/residents/'
      path: '/residents'
      fullPath: '/residents/'
      preLoaderRoute: typeof AuthenticatedResidentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/residents/$id': {
      id: '/_authenticated/residents/$id'
      path: '/residents/$id'
      fullPath: '/residents/$id'
      preLoaderRoute: typeof AuthenticatedResidentsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles/': {
      id: '/_authenticated/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof AuthenticatedRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tickets/': {
      id: '/_authenticated/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof AuthenticatedTicketsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedForumThreadIdRoute: typeof AuthenticatedForumThreadIdRoute
  AuthenticatedHousesIdRoute: typeof AuthenticatedHousesIdRoute
  AuthenticatedResidentsIdRoute: typeof AuthenticatedResidentsIdRoute
  AuthenticatedActivityLogsIndexRoute: typeof AuthenticatedActivityLogsIndexRoute
  AuthenticatedAnnouncementsIndexRoute: typeof AuthenticatedAnnouncementsIndexRoute
  AuthenticatedBillsIndexRoute: typeof AuthenticatedBillsIndexRoute
  AuthenticatedContactMessagesIndexRoute: typeof AuthenticatedContactMessagesIndexRoute
  AuthenticatedDueTypesIndexRoute: typeof AuthenticatedDueTypesIndexRoute
  AuthenticatedExpenseCategoriesIndexRoute: typeof AuthenticatedExpenseCategoriesIndexRoute
  AuthenticatedExpensesIndexRoute: typeof AuthenticatedExpensesIndexRoute
  AuthenticatedForumIndexRoute: typeof AuthenticatedForumIndexRoute
  AuthenticatedHousesIndexRoute: typeof AuthenticatedHousesIndexRoute
  AuthenticatedNotificationsIndexRoute: typeof AuthenticatedNotificationsIndexRoute
  AuthenticatedPagesIndexRoute: typeof AuthenticatedPagesIndexRoute
  AuthenticatedPaymentsIndexRoute: typeof AuthenticatedPaymentsIndexRoute
  AuthenticatedPengumumanIndexRoute: typeof AuthenticatedPengumumanIndexRoute
  AuthenticatedPermissionsIndexRoute: typeof AuthenticatedPermissionsIndexRoute
  AuthenticatedPollsIndexRoute: typeof AuthenticatedPollsIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedResidentsIndexRoute: typeof AuthenticatedResidentsIndexRoute
  AuthenticatedRolesIndexRoute: typeof AuthenticatedRolesIndexRoute
  AuthenticatedTicketsIndexRoute: typeof AuthenticatedTicketsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedForumThreadIdRoute: AuthenticatedForumThreadIdRoute,
  AuthenticatedHousesIdRoute: AuthenticatedHousesIdRoute,
  AuthenticatedResidentsIdRoute: AuthenticatedResidentsIdRoute,
  AuthenticatedActivityLogsIndexRoute: AuthenticatedActivityLogsIndexRoute,
  AuthenticatedAnnouncementsIndexRoute: AuthenticatedAnnouncementsIndexRoute,
  AuthenticatedBillsIndexRoute: AuthenticatedBillsIndexRoute,
  AuthenticatedContactMessagesIndexRoute:
    AuthenticatedContactMessagesIndexRoute,
  AuthenticatedDueTypesIndexRoute: AuthenticatedDueTypesIndexRoute,
  AuthenticatedExpenseCategoriesIndexRoute:
    AuthenticatedExpenseCategoriesIndexRoute,
  AuthenticatedExpensesIndexRoute: AuthenticatedExpensesIndexRoute,
  AuthenticatedForumIndexRoute: AuthenticatedForumIndexRoute,
  AuthenticatedHousesIndexRoute: AuthenticatedHousesIndexRoute,
  AuthenticatedNotificationsIndexRoute: AuthenticatedNotificationsIndexRoute,
  AuthenticatedPagesIndexRoute: AuthenticatedPagesIndexRoute,
  AuthenticatedPaymentsIndexRoute: AuthenticatedPaymentsIndexRoute,
  AuthenticatedPengumumanIndexRoute: AuthenticatedPengumumanIndexRoute,
  AuthenticatedPermissionsIndexRoute: AuthenticatedPermissionsIndexRoute,
  AuthenticatedPollsIndexRoute: AuthenticatedPollsIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedResidentsIndexRoute: AuthenticatedResidentsIndexRoute,
  AuthenticatedRolesIndexRoute: AuthenticatedRolesIndexRoute,
  AuthenticatedTicketsIndexRoute: AuthenticatedTicketsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
