/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedBillsIndexRouteImport } from './routes/_authenticated/bills/index'
import { Route as AuthenticatedDueTypesIndexRouteImport } from './routes/_authenticated/due-types/index'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedExpensesIndexRouteImport } from './routes/_authenticated/expenses/index'
import { Route as AuthenticatedHousesIndexRouteImport } from './routes/_authenticated/houses/index'
import { Route as AuthenticatedHousesIdRouteImport } from './routes/_authenticated/houses/$id'
import { Route as AuthenticatedPaymentsIndexRouteImport } from './routes/_authenticated/payments/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedResidentsIndexRouteImport } from './routes/_authenticated/residents/index'
import { Route as AuthenticatedResidentsIdRouteImport } from './routes/_authenticated/residents/$id'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillsIndexRoute = AuthenticatedBillsIndexRouteImport.update({
  id: '/bills/',
  path: '/bills/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDueTypesIndexRoute =
  AuthenticatedDueTypesIndexRouteImport.update({
    id: '/due-types/',
    path: '/due-types/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExpensesIndexRoute =
  AuthenticatedExpensesIndexRouteImport.update({
    id: '/expenses/',
    path: '/expenses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHousesIndexRoute =
  AuthenticatedHousesIndexRouteImport.update({
    id: '/houses/',
    path: '/houses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHousesIdRoute = AuthenticatedHousesIdRouteImport.update({
  id: '/houses/$id',
  path: '/houses/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsIndexRoute =
  AuthenticatedPaymentsIndexRouteImport.update({
    id: '/payments/',
    path: '/payments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResidentsIndexRoute =
  AuthenticatedResidentsIndexRouteImport.update({
    id: '/residents/',
    path: '/residents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResidentsIdRoute =
  AuthenticatedResidentsIdRouteImport.update({
    id: '/residents/$id',
    path: '/residents/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/houses/$id': typeof AuthenticatedHousesIdRoute
  '/residents/$id': typeof AuthenticatedResidentsIdRoute
  '/bills/': typeof AuthenticatedBillsIndexRoute
  '/due-types/': typeof AuthenticatedDueTypesIndexRoute
  '/expenses/': typeof AuthenticatedExpensesIndexRoute
  '/houses/': typeof AuthenticatedHousesIndexRoute
  '/payments/': typeof AuthenticatedPaymentsIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/residents/': typeof AuthenticatedResidentsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/houses/$id': typeof AuthenticatedHousesIdRoute
  '/residents/$id': typeof AuthenticatedResidentsIdRoute
  '/bills': typeof AuthenticatedBillsIndexRoute
  '/due-types': typeof AuthenticatedDueTypesIndexRoute
  '/expenses': typeof AuthenticatedExpensesIndexRoute
  '/houses': typeof AuthenticatedHousesIndexRoute
  '/payments': typeof AuthenticatedPaymentsIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/residents': typeof AuthenticatedResidentsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/houses/$id': typeof AuthenticatedHousesIdRoute
  '/_authenticated/residents/$id': typeof AuthenticatedResidentsIdRoute
  '/_authenticated/bills/': typeof AuthenticatedBillsIndexRoute
  '/_authenticated/due-types/': typeof AuthenticatedDueTypesIndexRoute
  '/_authenticated/expenses/': typeof AuthenticatedExpensesIndexRoute
  '/_authenticated/houses/': typeof AuthenticatedHousesIndexRoute
  '/_authenticated/payments/': typeof AuthenticatedPaymentsIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/residents/': typeof AuthenticatedResidentsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/errors/$error'
    | '/houses/$id'
    | '/residents/$id'
    | '/bills/'
    | '/due-types/'
    | '/expenses/'
    | '/houses/'
    | '/payments/'
    | '/reports/'
    | '/residents/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/houses/$id'
    | '/residents/$id'
    | '/bills'
    | '/due-types'
    | '/expenses'
    | '/houses'
    | '/payments'
    | '/reports'
    | '/residents'
    | '/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/houses/$id'
    | '/_authenticated/residents/$id'
    | '/_authenticated/bills/'
    | '/_authenticated/due-types/'
    | '/_authenticated/expenses/'
    | '/_authenticated/houses/'
    | '/_authenticated/payments/'
    | '/_authenticated/reports/'
    | '/_authenticated/residents/'
    | '/_authenticated/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bills/': {
      id: '/_authenticated/bills/'
      path: '/bills'
      fullPath: '/bills/'
      preLoaderRoute: typeof AuthenticatedBillsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/due-types/': {
      id: '/_authenticated/due-types/'
      path: '/due-types'
      fullPath: '/due-types/'
      preLoaderRoute: typeof AuthenticatedDueTypesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses/': {
      id: '/_authenticated/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof AuthenticatedExpensesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/houses/': {
      id: '/_authenticated/houses/'
      path: '/houses'
      fullPath: '/houses/'
      preLoaderRoute: typeof AuthenticatedHousesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/houses/$id': {
      id: '/_authenticated/houses/$id'
      path: '/houses/$id'
      fullPath: '/houses/$id'
      preLoaderRoute: typeof AuthenticatedHousesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments/': {
      id: '/_authenticated/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof AuthenticatedPaymentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/residents/': {
      id: '/_authenticated/residents/'
      path: '/residents'
      fullPath: '/residents/'
      preLoaderRoute: typeof AuthenticatedResidentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/residents/$id': {
      id: '/_authenticated/residents/$id'
      path: '/residents/$id'
      fullPath: '/residents/$id'
      preLoaderRoute: typeof AuthenticatedResidentsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedHousesIdRoute: typeof AuthenticatedHousesIdRoute
  AuthenticatedResidentsIdRoute: typeof AuthenticatedResidentsIdRoute
  AuthenticatedBillsIndexRoute: typeof AuthenticatedBillsIndexRoute
  AuthenticatedDueTypesIndexRoute: typeof AuthenticatedDueTypesIndexRoute
  AuthenticatedExpensesIndexRoute: typeof AuthenticatedExpensesIndexRoute
  AuthenticatedHousesIndexRoute: typeof AuthenticatedHousesIndexRoute
  AuthenticatedPaymentsIndexRoute: typeof AuthenticatedPaymentsIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedResidentsIndexRoute: typeof AuthenticatedResidentsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedHousesIdRoute: AuthenticatedHousesIdRoute,
  AuthenticatedResidentsIdRoute: AuthenticatedResidentsIdRoute,
  AuthenticatedBillsIndexRoute: AuthenticatedBillsIndexRoute,
  AuthenticatedDueTypesIndexRoute: AuthenticatedDueTypesIndexRoute,
  AuthenticatedExpensesIndexRoute: AuthenticatedExpensesIndexRoute,
  AuthenticatedHousesIndexRoute: AuthenticatedHousesIndexRoute,
  AuthenticatedPaymentsIndexRoute: AuthenticatedPaymentsIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedResidentsIndexRoute: AuthenticatedResidentsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
