/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as VerifikasiKeluargaTokenRouteImport } from './routes/verifikasi-keluarga.$token'
import { Route as AuthenticatedActivityLogsIndexRouteImport } from './routes/_authenticated/activity-logs/index'
import { Route as AuthenticatedAnnouncementsIndexRouteImport } from './routes/_authenticated/announcements/index'
import { Route as AuthenticatedAssetsIndexRouteImport } from './routes/_authenticated/assets/index'
import { Route as AuthenticatedBillsIndexRouteImport } from './routes/_authenticated/bills/index'
import { Route as AuthenticatedBookingsIndexRouteImport } from './routes/_authenticated/bookings/index'
import { Route as AuthenticatedCctvIndexRouteImport } from './routes/_authenticated/cctv/index'
import { Route as AuthenticatedContactMessagesIndexRouteImport } from './routes/_authenticated/contact-messages/index'
import { Route as AuthenticatedDueTypesIndexRouteImport } from './routes/_authenticated/due-types/index'
import { Route as AuthenticatedEmergencyContactsIndexRouteImport } from './routes/_authenticated/emergency-contacts/index'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedEventsIndexRouteImport } from './routes/_authenticated/events/index'
import { Route as AuthenticatedExpenseCategoriesIndexRouteImport } from './routes/_authenticated/expense-categories/index'
import { Route as AuthenticatedExpensesIndexRouteImport } from './routes/_authenticated/expenses/index'
import { Route as AuthenticatedExportsIndexRouteImport } from './routes/_authenticated/exports/index'
import { Route as AuthenticatedFacilitiesIndexRouteImport } from './routes/_authenticated/facilities/index'
import { Route as AuthenticatedFamilyIndexRouteImport } from './routes/_authenticated/family/index'
import { Route as AuthenticatedForumIndexRouteImport } from './routes/_authenticated/forum/index'
import { Route as AuthenticatedForumThreadIdRouteImport } from './routes/_authenticated/forum/$threadId'
import { Route as AuthenticatedGuestLogsIndexRouteImport } from './routes/_authenticated/guest-logs/index'
import { Route as AuthenticatedHousesIndexRouteImport } from './routes/_authenticated/houses/index'
import { Route as AuthenticatedHousesIdRouteImport } from './routes/_authenticated/houses/$id'
import { Route as AuthenticatedNotificationsIndexRouteImport } from './routes/_authenticated/notifications/index'
import { Route as AuthenticatedPagesIndexRouteImport } from './routes/_authenticated/pages/index'
import { Route as AuthenticatedPanicIndexRouteImport } from './routes/_authenticated/panic/index'
import { Route as AuthenticatedPatrolsIndexRouteImport } from './routes/_authenticated/patrols/index'
import { Route as AuthenticatedPaymentsOnlineIndexRouteImport } from './routes/_authenticated/payments-online/index'
import { Route as AuthenticatedPaymentsIndexRouteImport } from './routes/_authenticated/payments/index'
import { Route as AuthenticatedPengumumanIndexRouteImport } from './routes/_authenticated/pengumuman/index'
import { Route as AuthenticatedPermissionsIndexRouteImport } from './routes/_authenticated/permissions/index'
import { Route as AuthenticatedPollsIndexRouteImport } from './routes/_authenticated/polls/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedResidentsIndexRouteImport } from './routes/_authenticated/residents/index'
import { Route as AuthenticatedResidentsIdRouteImport } from './routes/_authenticated/residents/$id'
import { Route as AuthenticatedRolesIndexRouteImport } from './routes/_authenticated/roles/index'
import { Route as AuthenticatedSuggestionsIndexRouteImport } from './routes/_authenticated/suggestions/index'
import { Route as AuthenticatedTicketsIndexRouteImport } from './routes/_authenticated/tickets/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const VerifikasiKeluargaTokenRoute = VerifikasiKeluargaTokenRouteImport.update({
  id: '/verifikasi-keluarga/$token',
  path: '/verifikasi-keluarga/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivityLogsIndexRoute =
  AuthenticatedActivityLogsIndexRouteImport.update({
    id: '/activity-logs/',
    path: '/activity-logs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnnouncementsIndexRoute =
  AuthenticatedAnnouncementsIndexRouteImport.update({
    id: '/announcements/',
    path: '/announcements/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssetsIndexRoute =
  AuthenticatedAssetsIndexRouteImport.update({
    id: '/assets/',
    path: '/assets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBillsIndexRoute = AuthenticatedBillsIndexRouteImport.update({
  id: '/bills/',
  path: '/bills/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookingsIndexRoute =
  AuthenticatedBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCctvIndexRoute = AuthenticatedCctvIndexRouteImport.update({
  id: '/cctv/',
  path: '/cctv/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactMessagesIndexRoute =
  AuthenticatedContactMessagesIndexRouteImport.update({
    id: '/contact-messages/',
    path: '/contact-messages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDueTypesIndexRoute =
  AuthenticatedDueTypesIndexRouteImport.update({
    id: '/due-types/',
    path: '/due-types/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmergencyContactsIndexRoute =
  AuthenticatedEmergencyContactsIndexRouteImport.update({
    id: '/emergency-contacts/',
    path: '/emergency-contacts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsIndexRoute =
  AuthenticatedEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExpenseCategoriesIndexRoute =
  AuthenticatedExpenseCategoriesIndexRouteImport.update({
    id: '/expense-categories/',
    path: '/expense-categories/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExpensesIndexRoute =
  AuthenticatedExpensesIndexRouteImport.update({
    id: '/expenses/',
    path: '/expenses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExportsIndexRoute =
  AuthenticatedExportsIndexRouteImport.update({
    id: '/exports/',
    path: '/exports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFacilitiesIndexRoute =
  AuthenticatedFacilitiesIndexRouteImport.update({
    id: '/facilities/',
    path: '/facilities/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFamilyIndexRoute =
  AuthenticatedFamilyIndexRouteImport.update({
    id: '/family/',
    path: '/family/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedForumIndexRoute = AuthenticatedForumIndexRouteImport.update({
  id: '/forum/',
  path: '/forum/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedForumThreadIdRoute =
  AuthenticatedForumThreadIdRouteImport.update({
    id: '/forum/$threadId',
    path: '/forum/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGuestLogsIndexRoute =
  AuthenticatedGuestLogsIndexRouteImport.update({
    id: '/guest-logs/',
    path: '/guest-logs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHousesIndexRoute =
  AuthenticatedHousesIndexRouteImport.update({
    id: '/houses/',
    path: '/houses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHousesIdRoute = AuthenticatedHousesIdRouteImport.update({
  id: '/houses/$id',
  path: '/houses/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsIndexRoute =
  AuthenticatedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPagesIndexRoute = AuthenticatedPagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPanicIndexRoute = AuthenticatedPanicIndexRouteImport.update({
  id: '/panic/',
  path: '/panic/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatrolsIndexRoute =
  AuthenticatedPatrolsIndexRouteImport.update({
    id: '/patrols/',
    path: '/patrols/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentsOnlineIndexRoute =
  AuthenticatedPaymentsOnlineIndexRouteImport.update({
    id: '/payments-online/',
    path: '/payments-online/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentsIndexRoute =
  AuthenticatedPaymentsIndexRouteImport.update({
    id: '/payments/',
    path: '/payments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPengumumanIndexRoute =
  AuthenticatedPengumumanIndexRouteImport.update({
    id: '/pengumuman/',
    path: '/pengumuman/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPermissionsIndexRoute =
  AuthenticatedPermissionsIndexRouteImport.update({
    id: '/permissions/',
    path: '/permissions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPollsIndexRoute = AuthenticatedPollsIndexRouteImport.update({
  id: '/polls/',
  path: '/polls/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResidentsIndexRoute =
  AuthenticatedResidentsIndexRouteImport.update({
    id: '/residents/',
    path: '/residents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResidentsIdRoute =
  AuthenticatedResidentsIdRouteImport.update({
    id: '/residents/$id',
    path: '/residents/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRolesIndexRoute = AuthenticatedRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuggestionsIndexRoute =
  AuthenticatedSuggestionsIndexRouteImport.update({
    id: '/suggestions/',
    path: '/suggestions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTicketsIndexRoute =
  AuthenticatedTicketsIndexRouteImport.update({
    id: '/tickets/',
    path: '/tickets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/verifikasi-keluarga/$token': typeof VerifikasiKeluargaTokenRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/forum/$threadId': typeof AuthenticatedForumThreadIdRoute
  '/houses/$id': typeof AuthenticatedHousesIdRoute
  '/residents/$id': typeof AuthenticatedResidentsIdRoute
  '/activity-logs/': typeof AuthenticatedActivityLogsIndexRoute
  '/announcements/': typeof AuthenticatedAnnouncementsIndexRoute
  '/assets/': typeof AuthenticatedAssetsIndexRoute
  '/bills/': typeof AuthenticatedBillsIndexRoute
  '/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/cctv/': typeof AuthenticatedCctvIndexRoute
  '/contact-messages/': typeof AuthenticatedContactMessagesIndexRoute
  '/due-types/': typeof AuthenticatedDueTypesIndexRoute
  '/emergency-contacts/': typeof AuthenticatedEmergencyContactsIndexRoute
  '/events/': typeof AuthenticatedEventsIndexRoute
  '/expense-categories/': typeof AuthenticatedExpenseCategoriesIndexRoute
  '/expenses/': typeof AuthenticatedExpensesIndexRoute
  '/exports/': typeof AuthenticatedExportsIndexRoute
  '/facilities/': typeof AuthenticatedFacilitiesIndexRoute
  '/family/': typeof AuthenticatedFamilyIndexRoute
  '/forum/': typeof AuthenticatedForumIndexRoute
  '/guest-logs/': typeof AuthenticatedGuestLogsIndexRoute
  '/houses/': typeof AuthenticatedHousesIndexRoute
  '/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/pages/': typeof AuthenticatedPagesIndexRoute
  '/panic/': typeof AuthenticatedPanicIndexRoute
  '/patrols/': typeof AuthenticatedPatrolsIndexRoute
  '/payments-online/': typeof AuthenticatedPaymentsOnlineIndexRoute
  '/payments/': typeof AuthenticatedPaymentsIndexRoute
  '/pengumuman/': typeof AuthenticatedPengumumanIndexRoute
  '/permissions/': typeof AuthenticatedPermissionsIndexRoute
  '/polls/': typeof AuthenticatedPollsIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/residents/': typeof AuthenticatedResidentsIndexRoute
  '/roles/': typeof AuthenticatedRolesIndexRoute
  '/suggestions/': typeof AuthenticatedSuggestionsIndexRoute
  '/tickets/': typeof AuthenticatedTicketsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/verifikasi-keluarga/$token': typeof VerifikasiKeluargaTokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/forum/$threadId': typeof AuthenticatedForumThreadIdRoute
  '/houses/$id': typeof AuthenticatedHousesIdRoute
  '/residents/$id': typeof AuthenticatedResidentsIdRoute
  '/activity-logs': typeof AuthenticatedActivityLogsIndexRoute
  '/announcements': typeof AuthenticatedAnnouncementsIndexRoute
  '/assets': typeof AuthenticatedAssetsIndexRoute
  '/bills': typeof AuthenticatedBillsIndexRoute
  '/bookings': typeof AuthenticatedBookingsIndexRoute
  '/cctv': typeof AuthenticatedCctvIndexRoute
  '/contact-messages': typeof AuthenticatedContactMessagesIndexRoute
  '/due-types': typeof AuthenticatedDueTypesIndexRoute
  '/emergency-contacts': typeof AuthenticatedEmergencyContactsIndexRoute
  '/events': typeof AuthenticatedEventsIndexRoute
  '/expense-categories': typeof AuthenticatedExpenseCategoriesIndexRoute
  '/expenses': typeof AuthenticatedExpensesIndexRoute
  '/exports': typeof AuthenticatedExportsIndexRoute
  '/facilities': typeof AuthenticatedFacilitiesIndexRoute
  '/family': typeof AuthenticatedFamilyIndexRoute
  '/forum': typeof AuthenticatedForumIndexRoute
  '/guest-logs': typeof AuthenticatedGuestLogsIndexRoute
  '/houses': typeof AuthenticatedHousesIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/pages': typeof AuthenticatedPagesIndexRoute
  '/panic': typeof AuthenticatedPanicIndexRoute
  '/patrols': typeof AuthenticatedPatrolsIndexRoute
  '/payments-online': typeof AuthenticatedPaymentsOnlineIndexRoute
  '/payments': typeof AuthenticatedPaymentsIndexRoute
  '/pengumuman': typeof AuthenticatedPengumumanIndexRoute
  '/permissions': typeof AuthenticatedPermissionsIndexRoute
  '/polls': typeof AuthenticatedPollsIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/residents': typeof AuthenticatedResidentsIndexRoute
  '/roles': typeof AuthenticatedRolesIndexRoute
  '/suggestions': typeof AuthenticatedSuggestionsIndexRoute
  '/tickets': typeof AuthenticatedTicketsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/verifikasi-keluarga/$token': typeof VerifikasiKeluargaTokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/forum/$threadId': typeof AuthenticatedForumThreadIdRoute
  '/_authenticated/houses/$id': typeof AuthenticatedHousesIdRoute
  '/_authenticated/residents/$id': typeof AuthenticatedResidentsIdRoute
  '/_authenticated/activity-logs/': typeof AuthenticatedActivityLogsIndexRoute
  '/_authenticated/announcements/': typeof AuthenticatedAnnouncementsIndexRoute
  '/_authenticated/assets/': typeof AuthenticatedAssetsIndexRoute
  '/_authenticated/bills/': typeof AuthenticatedBillsIndexRoute
  '/_authenticated/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/_authenticated/cctv/': typeof AuthenticatedCctvIndexRoute
  '/_authenticated/contact-messages/': typeof AuthenticatedContactMessagesIndexRoute
  '/_authenticated/due-types/': typeof AuthenticatedDueTypesIndexRoute
  '/_authenticated/emergency-contacts/': typeof AuthenticatedEmergencyContactsIndexRoute
  '/_authenticated/events/': typeof AuthenticatedEventsIndexRoute
  '/_authenticated/expense-categories/': typeof AuthenticatedExpenseCategoriesIndexRoute
  '/_authenticated/expenses/': typeof AuthenticatedExpensesIndexRoute
  '/_authenticated/exports/': typeof AuthenticatedExportsIndexRoute
  '/_authenticated/facilities/': typeof AuthenticatedFacilitiesIndexRoute
  '/_authenticated/family/': typeof AuthenticatedFamilyIndexRoute
  '/_authenticated/forum/': typeof AuthenticatedForumIndexRoute
  '/_authenticated/guest-logs/': typeof AuthenticatedGuestLogsIndexRoute
  '/_authenticated/houses/': typeof AuthenticatedHousesIndexRoute
  '/_authenticated/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/_authenticated/pages/': typeof AuthenticatedPagesIndexRoute
  '/_authenticated/panic/': typeof AuthenticatedPanicIndexRoute
  '/_authenticated/patrols/': typeof AuthenticatedPatrolsIndexRoute
  '/_authenticated/payments-online/': typeof AuthenticatedPaymentsOnlineIndexRoute
  '/_authenticated/payments/': typeof AuthenticatedPaymentsIndexRoute
  '/_authenticated/pengumuman/': typeof AuthenticatedPengumumanIndexRoute
  '/_authenticated/permissions/': typeof AuthenticatedPermissionsIndexRoute
  '/_authenticated/polls/': typeof AuthenticatedPollsIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/residents/': typeof AuthenticatedResidentsIndexRoute
  '/_authenticated/roles/': typeof AuthenticatedRolesIndexRoute
  '/_authenticated/suggestions/': typeof AuthenticatedSuggestionsIndexRoute
  '/_authenticated/tickets/': typeof AuthenticatedTicketsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/verifikasi-keluarga/$token'
    | '/errors/$error'
    | '/forum/$threadId'
    | '/houses/$id'
    | '/residents/$id'
    | '/activity-logs/'
    | '/announcements/'
    | '/assets/'
    | '/bills/'
    | '/bookings/'
    | '/cctv/'
    | '/contact-messages/'
    | '/due-types/'
    | '/emergency-contacts/'
    | '/events/'
    | '/expense-categories/'
    | '/expenses/'
    | '/exports/'
    | '/facilities/'
    | '/family/'
    | '/forum/'
    | '/guest-logs/'
    | '/houses/'
    | '/notifications/'
    | '/pages/'
    | '/panic/'
    | '/patrols/'
    | '/payments-online/'
    | '/payments/'
    | '/pengumuman/'
    | '/permissions/'
    | '/polls/'
    | '/reports/'
    | '/residents/'
    | '/roles/'
    | '/suggestions/'
    | '/tickets/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/verifikasi-keluarga/$token'
    | '/'
    | '/errors/$error'
    | '/forum/$threadId'
    | '/houses/$id'
    | '/residents/$id'
    | '/activity-logs'
    | '/announcements'
    | '/assets'
    | '/bills'
    | '/bookings'
    | '/cctv'
    | '/contact-messages'
    | '/due-types'
    | '/emergency-contacts'
    | '/events'
    | '/expense-categories'
    | '/expenses'
    | '/exports'
    | '/facilities'
    | '/family'
    | '/forum'
    | '/guest-logs'
    | '/houses'
    | '/notifications'
    | '/pages'
    | '/panic'
    | '/patrols'
    | '/payments-online'
    | '/payments'
    | '/pengumuman'
    | '/permissions'
    | '/polls'
    | '/reports'
    | '/residents'
    | '/roles'
    | '/suggestions'
    | '/tickets'
    | '/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/verifikasi-keluarga/$token'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/forum/$threadId'
    | '/_authenticated/houses/$id'
    | '/_authenticated/residents/$id'
    | '/_authenticated/activity-logs/'
    | '/_authenticated/announcements/'
    | '/_authenticated/assets/'
    | '/_authenticated/bills/'
    | '/_authenticated/bookings/'
    | '/_authenticated/cctv/'
    | '/_authenticated/contact-messages/'
    | '/_authenticated/due-types/'
    | '/_authenticated/emergency-contacts/'
    | '/_authenticated/events/'
    | '/_authenticated/expense-categories/'
    | '/_authenticated/expenses/'
    | '/_authenticated/exports/'
    | '/_authenticated/facilities/'
    | '/_authenticated/family/'
    | '/_authenticated/forum/'
    | '/_authenticated/guest-logs/'
    | '/_authenticated/houses/'
    | '/_authenticated/notifications/'
    | '/_authenticated/pages/'
    | '/_authenticated/panic/'
    | '/_authenticated/patrols/'
    | '/_authenticated/payments-online/'
    | '/_authenticated/payments/'
    | '/_authenticated/pengumuman/'
    | '/_authenticated/permissions/'
    | '/_authenticated/polls/'
    | '/_authenticated/reports/'
    | '/_authenticated/residents/'
    | '/_authenticated/roles/'
    | '/_authenticated/suggestions/'
    | '/_authenticated/tickets/'
    | '/_authenticated/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  VerifikasiKeluargaTokenRoute: typeof VerifikasiKeluargaTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/verifikasi-keluarga/$token': {
      id: '/verifikasi-keluarga/$token'
      path: '/verifikasi-keluarga/$token'
      fullPath: '/verifikasi-keluarga/$token'
      preLoaderRoute: typeof VerifikasiKeluargaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activity-logs/': {
      id: '/_authenticated/activity-logs/'
      path: '/activity-logs'
      fullPath: '/activity-logs/'
      preLoaderRoute: typeof AuthenticatedActivityLogsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/announcements/': {
      id: '/_authenticated/announcements/'
      path: '/announcements'
      fullPath: '/announcements/'
      preLoaderRoute: typeof AuthenticatedAnnouncementsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assets/': {
      id: '/_authenticated/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AuthenticatedAssetsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bills/': {
      id: '/_authenticated/bills/'
      path: '/bills'
      fullPath: '/bills/'
      preLoaderRoute: typeof AuthenticatedBillsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings/': {
      id: '/_authenticated/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof AuthenticatedBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cctv/': {
      id: '/_authenticated/cctv/'
      path: '/cctv'
      fullPath: '/cctv/'
      preLoaderRoute: typeof AuthenticatedCctvIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contact-messages/': {
      id: '/_authenticated/contact-messages/'
      path: '/contact-messages'
      fullPath: '/contact-messages/'
      preLoaderRoute: typeof AuthenticatedContactMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/due-types/': {
      id: '/_authenticated/due-types/'
      path: '/due-types'
      fullPath: '/due-types/'
      preLoaderRoute: typeof AuthenticatedDueTypesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/emergency-contacts/': {
      id: '/_authenticated/emergency-contacts/'
      path: '/emergency-contacts'
      fullPath: '/emergency-contacts/'
      preLoaderRoute: typeof AuthenticatedEmergencyContactsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/': {
      id: '/_authenticated/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AuthenticatedEventsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expense-categories/': {
      id: '/_authenticated/expense-categories/'
      path: '/expense-categories'
      fullPath: '/expense-categories/'
      preLoaderRoute: typeof AuthenticatedExpenseCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses/': {
      id: '/_authenticated/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof AuthenticatedExpensesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exports/': {
      id: '/_authenticated/exports/'
      path: '/exports'
      fullPath: '/exports/'
      preLoaderRoute: typeof AuthenticatedExportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/facilities/': {
      id: '/_authenticated/facilities/'
      path: '/facilities'
      fullPath: '/facilities/'
      preLoaderRoute: typeof AuthenticatedFacilitiesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/family/': {
      id: '/_authenticated/family/'
      path: '/family'
      fullPath: '/family/'
      preLoaderRoute: typeof AuthenticatedFamilyIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forum/': {
      id: '/_authenticated/forum/'
      path: '/forum'
      fullPath: '/forum/'
      preLoaderRoute: typeof AuthenticatedForumIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forum/$threadId': {
      id: '/_authenticated/forum/$threadId'
      path: '/forum/$threadId'
      fullPath: '/forum/$threadId'
      preLoaderRoute: typeof AuthenticatedForumThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guest-logs/': {
      id: '/_authenticated/guest-logs/'
      path: '/guest-logs'
      fullPath: '/guest-logs/'
      preLoaderRoute: typeof AuthenticatedGuestLogsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/houses/': {
      id: '/_authenticated/houses/'
      path: '/houses'
      fullPath: '/houses/'
      preLoaderRoute: typeof AuthenticatedHousesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/houses/$id': {
      id: '/_authenticated/houses/$id'
      path: '/houses/$id'
      fullPath: '/houses/$id'
      preLoaderRoute: typeof AuthenticatedHousesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications/': {
      id: '/_authenticated/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AuthenticatedNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pages/': {
      id: '/_authenticated/pages/'
      path: '/pages'
      fullPath: '/pages/'
      preLoaderRoute: typeof AuthenticatedPagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panic/': {
      id: '/_authenticated/panic/'
      path: '/panic'
      fullPath: '/panic/'
      preLoaderRoute: typeof AuthenticatedPanicIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patrols/': {
      id: '/_authenticated/patrols/'
      path: '/patrols'
      fullPath: '/patrols/'
      preLoaderRoute: typeof AuthenticatedPatrolsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments-online/': {
      id: '/_authenticated/payments-online/'
      path: '/payments-online'
      fullPath: '/payments-online/'
      preLoaderRoute: typeof AuthenticatedPaymentsOnlineIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments/': {
      id: '/_authenticated/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof AuthenticatedPaymentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pengumuman/': {
      id: '/_authenticated/pengumuman/'
      path: '/pengumuman'
      fullPath: '/pengumuman/'
      preLoaderRoute: typeof AuthenticatedPengumumanIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permissions/': {
      id: '/_authenticated/permissions/'
      path: '/permissions'
      fullPath: '/permissions/'
      preLoaderRoute: typeof AuthenticatedPermissionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/polls/': {
      id: '/_authenticated/polls/'
      path: '/polls'
      fullPath: '/polls/'
      preLoaderRoute: typeof AuthenticatedPollsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/residents/': {
      id: '/_authenticated/residents/'
      path: '/residents'
      fullPath: '/residents/'
      preLoaderRoute: typeof AuthenticatedResidentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/residents/$id': {
      id: '/_authenticated/residents/$id'
      path: '/residents/$id'
      fullPath: '/residents/$id'
      preLoaderRoute: typeof AuthenticatedResidentsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles/': {
      id: '/_authenticated/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof AuthenticatedRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suggestions/': {
      id: '/_authenticated/suggestions/'
      path: '/suggestions'
      fullPath: '/suggestions/'
      preLoaderRoute: typeof AuthenticatedSuggestionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tickets/': {
      id: '/_authenticated/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof AuthenticatedTicketsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedForumThreadIdRoute: typeof AuthenticatedForumThreadIdRoute
  AuthenticatedHousesIdRoute: typeof AuthenticatedHousesIdRoute
  AuthenticatedResidentsIdRoute: typeof AuthenticatedResidentsIdRoute
  AuthenticatedActivityLogsIndexRoute: typeof AuthenticatedActivityLogsIndexRoute
  AuthenticatedAnnouncementsIndexRoute: typeof AuthenticatedAnnouncementsIndexRoute
  AuthenticatedAssetsIndexRoute: typeof AuthenticatedAssetsIndexRoute
  AuthenticatedBillsIndexRoute: typeof AuthenticatedBillsIndexRoute
  AuthenticatedBookingsIndexRoute: typeof AuthenticatedBookingsIndexRoute
  AuthenticatedCctvIndexRoute: typeof AuthenticatedCctvIndexRoute
  AuthenticatedContactMessagesIndexRoute: typeof AuthenticatedContactMessagesIndexRoute
  AuthenticatedDueTypesIndexRoute: typeof AuthenticatedDueTypesIndexRoute
  AuthenticatedEmergencyContactsIndexRoute: typeof AuthenticatedEmergencyContactsIndexRoute
  AuthenticatedEventsIndexRoute: typeof AuthenticatedEventsIndexRoute
  AuthenticatedExpenseCategoriesIndexRoute: typeof AuthenticatedExpenseCategoriesIndexRoute
  AuthenticatedExpensesIndexRoute: typeof AuthenticatedExpensesIndexRoute
  AuthenticatedExportsIndexRoute: typeof AuthenticatedExportsIndexRoute
  AuthenticatedFacilitiesIndexRoute: typeof AuthenticatedFacilitiesIndexRoute
  AuthenticatedFamilyIndexRoute: typeof AuthenticatedFamilyIndexRoute
  AuthenticatedForumIndexRoute: typeof AuthenticatedForumIndexRoute
  AuthenticatedGuestLogsIndexRoute: typeof AuthenticatedGuestLogsIndexRoute
  AuthenticatedHousesIndexRoute: typeof AuthenticatedHousesIndexRoute
  AuthenticatedNotificationsIndexRoute: typeof AuthenticatedNotificationsIndexRoute
  AuthenticatedPagesIndexRoute: typeof AuthenticatedPagesIndexRoute
  AuthenticatedPanicIndexRoute: typeof AuthenticatedPanicIndexRoute
  AuthenticatedPatrolsIndexRoute: typeof AuthenticatedPatrolsIndexRoute
  AuthenticatedPaymentsOnlineIndexRoute: typeof AuthenticatedPaymentsOnlineIndexRoute
  AuthenticatedPaymentsIndexRoute: typeof AuthenticatedPaymentsIndexRoute
  AuthenticatedPengumumanIndexRoute: typeof AuthenticatedPengumumanIndexRoute
  AuthenticatedPermissionsIndexRoute: typeof AuthenticatedPermissionsIndexRoute
  AuthenticatedPollsIndexRoute: typeof AuthenticatedPollsIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedResidentsIndexRoute: typeof AuthenticatedResidentsIndexRoute
  AuthenticatedRolesIndexRoute: typeof AuthenticatedRolesIndexRoute
  AuthenticatedSuggestionsIndexRoute: typeof AuthenticatedSuggestionsIndexRoute
  AuthenticatedTicketsIndexRoute: typeof AuthenticatedTicketsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedForumThreadIdRoute: AuthenticatedForumThreadIdRoute,
  AuthenticatedHousesIdRoute: AuthenticatedHousesIdRoute,
  AuthenticatedResidentsIdRoute: AuthenticatedResidentsIdRoute,
  AuthenticatedActivityLogsIndexRoute: AuthenticatedActivityLogsIndexRoute,
  AuthenticatedAnnouncementsIndexRoute: AuthenticatedAnnouncementsIndexRoute,
  AuthenticatedAssetsIndexRoute: AuthenticatedAssetsIndexRoute,
  AuthenticatedBillsIndexRoute: AuthenticatedBillsIndexRoute,
  AuthenticatedBookingsIndexRoute: AuthenticatedBookingsIndexRoute,
  AuthenticatedCctvIndexRoute: AuthenticatedCctvIndexRoute,
  AuthenticatedContactMessagesIndexRoute:
    AuthenticatedContactMessagesIndexRoute,
  AuthenticatedDueTypesIndexRoute: AuthenticatedDueTypesIndexRoute,
  AuthenticatedEmergencyContactsIndexRoute:
    AuthenticatedEmergencyContactsIndexRoute,
  AuthenticatedEventsIndexRoute: AuthenticatedEventsIndexRoute,
  AuthenticatedExpenseCategoriesIndexRoute:
    AuthenticatedExpenseCategoriesIndexRoute,
  AuthenticatedExpensesIndexRoute: AuthenticatedExpensesIndexRoute,
  AuthenticatedExportsIndexRoute: AuthenticatedExportsIndexRoute,
  AuthenticatedFacilitiesIndexRoute: AuthenticatedFacilitiesIndexRoute,
  AuthenticatedFamilyIndexRoute: AuthenticatedFamilyIndexRoute,
  AuthenticatedForumIndexRoute: AuthenticatedForumIndexRoute,
  AuthenticatedGuestLogsIndexRoute: AuthenticatedGuestLogsIndexRoute,
  AuthenticatedHousesIndexRoute: AuthenticatedHousesIndexRoute,
  AuthenticatedNotificationsIndexRoute: AuthenticatedNotificationsIndexRoute,
  AuthenticatedPagesIndexRoute: AuthenticatedPagesIndexRoute,
  AuthenticatedPanicIndexRoute: AuthenticatedPanicIndexRoute,
  AuthenticatedPatrolsIndexRoute: AuthenticatedPatrolsIndexRoute,
  AuthenticatedPaymentsOnlineIndexRoute: AuthenticatedPaymentsOnlineIndexRoute,
  AuthenticatedPaymentsIndexRoute: AuthenticatedPaymentsIndexRoute,
  AuthenticatedPengumumanIndexRoute: AuthenticatedPengumumanIndexRoute,
  AuthenticatedPermissionsIndexRoute: AuthenticatedPermissionsIndexRoute,
  AuthenticatedPollsIndexRoute: AuthenticatedPollsIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedResidentsIndexRoute: AuthenticatedResidentsIndexRoute,
  AuthenticatedRolesIndexRoute: AuthenticatedRolesIndexRoute,
  AuthenticatedSuggestionsIndexRoute: AuthenticatedSuggestionsIndexRoute,
  AuthenticatedTicketsIndexRoute: AuthenticatedTicketsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  VerifikasiKeluargaTokenRoute: VerifikasiKeluargaTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
